name: Update Image Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at midnigth UTC everyday
    - cron: "0 0 * * *"

#jobs:
#  update-readme:
#    name: Update Image README
#    runs-on: ubuntu-latest
#    steps:
#      - uses: siddharth2016/update-readme-image@main
#        with:
#          IMG_ALT: Image ALT
